
package ru.terralink.ws.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SyncService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/Users/Aksndr/Desktop/\u041d\u041d/SyncService.svc.wsdl")
public class SyncService
    extends Service
{

    private final static URL SYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYNCSERVICE_EXCEPTION;
    private final static QName SYNCSERVICE_QNAME = new QName("http://tempuri.org/", "SyncService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Aksndr/Desktop/\u041d\u041d/SyncService.svc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYNCSERVICE_WSDL_LOCATION = url;
        SYNCSERVICE_EXCEPTION = e;
    }

    public SyncService() {
        super(__getWsdlLocation(), SYNCSERVICE_QNAME);
    }

    public SyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYNCSERVICE_QNAME, features);
    }

    public SyncService(URL wsdlLocation) {
        super(wsdlLocation, SYNCSERVICE_QNAME);
    }

    public SyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYNCSERVICE_QNAME, features);
    }

    public SyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISyncService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISyncService")
    public ISyncService getBasicHttpBindingISyncService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISyncService"), ISyncService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISyncService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISyncService")
    public ISyncService getBasicHttpBindingISyncService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISyncService"), ISyncService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYNCSERVICE_EXCEPTION!= null) {
            throw SYNCSERVICE_EXCEPTION;
        }
        return SYNCSERVICE_WSDL_LOCATION;
    }

}
